
/**
 * Solves the Fibonacci problem
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * Ruhika Chatterjee
 * 10/21/2016
 */
public class RC_EvenFibPE2
{
    public static void main (String args [])
    {
        int sum = 0;
        int last = 0;
        int fib = 1;
        int h;
        while (fib+last < 4000000){
            h = fib;
            fib += last;
            last = h;
            if (fib % 2 == 0) sum += fib;
        }
        System.out.println ("The sum of all even Fibonacci numbers less than 4,000,000 is " + sum);
    }
}
/*
 * Output: The sum of all even Fibonacci numbers less than 4,000,000 is 4613732
 */